# Generated by Django 4.2.4 on 2023-08-06 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0002_todo_notes"),
    ]

    operations = [
        migrations.AddField(
            model_name="todo",
            name="status",
            field=models.CharField(
                choices=[
                    ("todo", "todo"),
                    ("finished", "finished"),
                    ("inprogress", "inprogress"),
                ],
                default="todo",
                max_length=130,
            ),
        ),
    ]
